datasources:
  - name: Prometheus
    uid: go-web-api
    type: prometheus
    access: proxy
    # Uses the Prometheus container name and internal port
    url: https://prometheus:9090
    isDefault: true
