apiVersion: 1

datasources:
  - name: Jaeger
    uid: jaeger
    type: jaeger
    access: proxy
    url: https://jaeger:16686
    editable: true
    isDefault: true
    jsonData:
      tlsSkipVerify: false
      tlsAuthWithCACert: true
      tlsAuth: true
      serverName: jaeger
    secureJsonData:
      tlsCACert: $LOCALHOST_CA_CERT
      tlsClientCert: $GRAFANA_CLIENT_CERT
      tlsClientKey: $GRAFANA_CLIENT_KEY
