apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: go-web-api-static-secret
  namespace: go-web-api
spec:
  vaultAuthRef: go-web-api-static-auth
  namespace: go-web-api
  mount: kv-v2
  type: kv-v2
  path: go-web-api/config
  refreshAfter: 10s
  destination:
    create: true
    name: config
  rolloutRestartTargets:
  - kind: Deployment
    name: go-web-api
